### ISSUE TITLE
Deprecated selector in `itg-flat-flatland-Monokai\index.less`

### ISSUE THREAD

**Issue by gostrafx** [ronilaukkarinen/itg-flat-flatland-monokai#2]
In `itg-flat-flatland-Monokai\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.source.cpp .entity.name.type.cpp` => `.syntax--source.syntax--cpp .syntax--entity.syntax--name.syntax--type.syntax--cpp`

* `.source.cpp .storage.type` => `.syntax--source.syntax--cpp .syntax--storage.syntax--type`

* `.source.cpp .support.function.any-method` => `.syntax--source.syntax--cpp .syntax--support.syntax--function.syntax--any-method`

* `.entity.name.function.c` => `.syntax--entity.syntax--name.syntax--function.syntax--c`

* `.support.function.any-method.c` => `.syntax--support.syntax--function.syntax--any-method.syntax--c`

* `.source.cs .entity.name.type.class` => `.syntax--source.syntax--cs .syntax--entity.syntax--name.syntax--type.syntax--class`

* `.source.cs .entity.name.type.namespace` => `.syntax--source.syntax--cs .syntax--entity.syntax--name.syntax--type.syntax--namespace`

* `.source.cs .meta.method-call` => `.syntax--source.syntax--cs .syntax--meta.syntax--method-call`

* `.source.cs .meta.namespace` => `.syntax--source.syntax--cs .syntax--meta.syntax--namespace`

* `.source.cs .meta.namespace.body` => `.syntax--source.syntax--cs .syntax--meta.syntax--namespace.syntax--body`

* `.source.cs .punctuation.definition` => `.syntax--source.syntax--cs .syntax--punctuation.syntax--definition`

* `.source.cs .punctuation.definition.comment` => `.syntax--source.syntax--cs .syntax--punctuation.syntax--definition.syntax--comment`

* `.source.cs .punctuation.definition.string` => `.syntax--source.syntax--cs .syntax--punctuation.syntax--definition.syntax--string`

* `.source.cs .punctuation.section` => `.syntax--source.syntax--cs .syntax--punctuation.syntax--section`

* `.source.cs .variable.parameter.function` => `.syntax--source.syntax--cs .syntax--variable.syntax--parameter.syntax--function`

* `.source.gfm .markup.bold` => `.syntax--source.syntax--gfm .syntax--markup.syntax--bold`

* `.source.gfm .markup.bold.italic` => `.syntax--source.syntax--gfm .syntax--markup.syntax--bold.syntax--italic`

* `.source.gfm .markup.constant.character.entity` => `.syntax--source.syntax--gfm .syntax--markup.syntax--constant.syntax--character.syntax--entity`

* `.source.gfm .markup.entity` => `.syntax--source.syntax--gfm .syntax--markup.syntax--entity`

* `.source.gfm .markup.heading` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading`

* `.source.gfm .markup.italic` => `.syntax--source.syntax--gfm .syntax--markup.syntax--italic`

* `.source.gfm .markup.raw` => `.syntax--source.syntax--gfm .syntax--markup.syntax--raw`

* `.source.gfm .markup.underline.link` => `.syntax--source.syntax--gfm .syntax--markup.syntax--underline.syntax--link`

* `[data-grammar*="gfm"]::shadow .markup.underline.link.https.hyperlink` => `[data-grammar*="gfm"]::shadow .syntax--markup.syntax--underline.syntax--link.https.syntax--hyperlink`

* `[data-grammar*="gfm"]::shadow .markup.underline.link span.punctuation` => `[data-grammar*="gfm"]::shadow .syntax--markup.syntax--underline.syntax--link span.syntax--punctuation`

* `[data-grammar*="gfm"]::shadow .punctuation.definition.begin,
[data-grammar*="gfm"]::shadow .punctuation.definition.end`

**Comment by rollecode** [comment]
This is related to [#1](https://github.com/ronilaukkarinen/itg-flat-flatland-monokai/issues/1) but I'm no longer Atom user so pull requests are welcome.
